name: ci

on: [pull_request]

jobs:
  db:
    runs-on: ubuntu-latest
    name: merge-db
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install packeges
        run: pip install -r requirements.txt
      - name: Run Python
        run: python merge_db.py
      - name: Push auto-fixed files
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .; \
          git commit -m "👕 Fixed auto-fixable textlint errors by github-actions"; \
          git push origin HEAD:${GITHUB_REF}; \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Commit db changes
      #   run: |
      #     git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
      #     git config --global user.name "${GITHUB_ACTOR}"
      #     git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      #     git add test.json
      #     git commit -m'update json by github actions'
      #     git push origin HEAD:${GITHUB_REF}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


