name: ci

on: [pull_request]

jobs:
  db:
    runs-on: ubuntu-latest
    name: merge-db
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install packeges
        run: pip install -r requirements.txt
      - name: Run Python
        run: python merge_db.py
      - name: Push changed db file
        run: |
          set -x
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add ./data/main.json
          git commit -m "automatically changed by github actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
